# Generated by Django 6.0.6 on 2026-06-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=500)),
                ('options', models.JSONField()),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
